# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Coffe(object):
    def setupUi(self, Coffe):
        Coffe.setObjectName("Coffe")
        Coffe.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Coffe)
        self.centralwidget.setObjectName("centralwidget")
        self.coffe_manager = QtWidgets.QLabel(parent=self.centralwidget)
        self.coffe_manager.setGeometry(QtCore.QRect(30, 20, 740, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.coffe_manager.setFont(font)
        self.coffe_manager.setObjectName("coffe_manager")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 100, 742, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_coffe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_coffe.setGeometry(QtCore.QRect(410, 30, 171, 51))
        self.add_coffe.setObjectName("add_coffe")
        Coffe.setCentralWidget(self.centralwidget)

        self.retranslateUi(Coffe)
        QtCore.QMetaObject.connectSlotsByName(Coffe)

    def retranslateUi(self, Coffe):
        _translate = QtCore.QCoreApplication.translate
        Coffe.setWindowTitle(_translate("Coffe", "MainWindow"))
        self.coffe_manager.setText(_translate("Coffe", "Coffe manager"))
        self.add_coffe.setText(_translate("Coffe", "Добавить котэ"))
